### ISSUE TITLE
Export commenter emails from the site in a form that can be imported into MailChimp

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-rivard-report#10]
1. Go to http://therivardreport.com/

EXPECT: Generate an export of previous commenters (emails) that you could import into MailChimp.

**Comment by rclations** [comment]
This strikes me as unethical because these users have not opted in to receive emails.

Obtaining permission from subscribers who want to receive your email campaigns is not only a courtesy, it's a requirement of MailChimps terms of service, as well as a legal requirement of many countries (esp. those in Europe).

For more information:
http://kb.mailchimp.com/accounts/compliance-tips/the-importance-of-permission
http://kb.mailchimp.com/accounts/compliance-tips/terms-of-use-and-anti-spam-requirements

**Comment by benlk** [comment]
If we export the addresses, and provide them with strong recommendations to not do he import, that covers both bases. They may want the emails for other purposes.

Just email addresses, or do we want any other info for this dump?

**Comment by kaylima** [comment]
First, Last, email and user created timestamp, please!

**Comment by benlk** [comment]
There's two sets of information that we can provide:

- raw comment authorship data: display name, email address, comment time
- account information: display name, email address, login name, account creation time - this is limited only to commenters with WordPress accounts.

Kay, I'm emailing you a pair of CSVs that contain both.

1. The first contains display name, email address, and comment time for the ~19,000 comments that were accepted on the site (as opposed to rejected or judged spam) and that have both display names and email addresses. I didn't deduplicate here because Rivard can use the number of comments to figure out who their most-engaged readers, and whether anyone is still commenting. Users who commented via Facebook had names ("Jane Q. Public via Facebook") but no email addresses, and are therefore excluded from this data set.
2. The second contains email address, display name, login name, and account creation date/time for those commenters who had WordPress accounts at some time. This is deduplicated.

The names here aren't reliable; we're pretty much dealing with whatever was put into the fields when the user registered. `earthmom2000` wanted to be known as that.

**Comment by rclations** [comment]
I don't understand why this ticket is proceeding and I would like it to stop until there is an established use case that passes an ethical test.
