### ISSUE TITLE
Add Mailchimp suppression to Modal behavior

### ISSUE THREAD

**Issue by julia67** [INN/umbrella-rivard-report#15]
See helpscout [#1110](https://secure.helpscout.net/conversation/403206135/1110/?folderId=1259186)

Desired behavior: The modal popup should not display if the user arrived at the page via a MailChimp link.

Pseudocode:
```
function displayNewsletterSignupModal() {
// RULE: Do not display the newsletter signup modal if the user landed on the Rivard site from a link in a MailChimp newsletter.
if (window.location.href.match(/utm_source=Rivard\+Report/i)) {
    return;
}
``` 

Comb through these plugin files for an example of how it's done:
[vosd-newsletter-list.zip](https://github.com/INN/umbrella-rivard-report/files/1322743/vosd-newsletter-list.zip)

**Comment by benlk** [comment]
This can be done natively within the plugin through the paid extension [Advanced Targeting Conditions](https://wppopupmaker.com/extensions/advanced-targeting-conditions/), or we build something custom that won't be as configurable.

If we take the plugin route, I can set the configuration on staging according to the terms.

Or I can copy the VOSD stuff in.

**Comment by julia67** [comment]
Let's go the VOSD route for this one.
