### ISSUE TITLE
Donor logos for Businesses and Nonprofits

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-rivard-report#20]
1. Go to: https://therivardreport.com/membership-donate/ (privately published)

RESULT: Doesn't have list of donors yet
EXPECT: Rivard would like something similar to "OUR MEMBERS" here: https://inn.org/ to appear at the bottom of the page (below the tabs of info)

NOTES:
- needs to be easily updatable and using a class in the text editor may not be ideal
- should include business and nonprofit logos from here: https://therivardreport.com/business-members/
- will need to decide how to handle the donation amounts (group them, show $ amount above or below logo, etc.)

![screen shot 2018-05-07 at 9 30 36 am](https://user-images.githubusercontent.com/15877728/39710220-699d3f04-51d9-11e8-9dce-1231df3dbdce.png)

**Comment by tylermachado** [comment]
Setting this up such that donors are based on custom post types, a la the INN Members that are registered in the INN theme in inc/member-directory.php.

Custom fields will include the donor URL and its donor amount. For the latter reason I would suggest grouping the donation amounts, and then ordering the donors in each grouping by donation amount descending, and then name ascending.

**Comment by tylermachado** [comment]
One other note: i'm making a new page template as well to include the grid feature.

**Comment by tylermachado** [comment]
This will also require the CMB2 plugin for custom fields on the new post type.
