### ISSUE TITLE
Capture emails from WordPress comments and integrate with MailChimp

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-rivard-report#7]
ESTIMATE: 4-6 hours

(previously, https://github.com/INN/umbrella-rivard-report/issues/10 was part of this ticket)

Go to http://rrlargo.staging.wpengine.com/

EXPECT: Add a MailChimp opt-in checkbox into the commenting form in WordPress, as shown here:

<img width="712" alt="comment-email" src="https://user-images.githubusercontent.com/15877728/29080366-ce93dcc6-7c1c-11e7-8a5d-bd0b31679060.png">

**Comment by benlk** [comment]
Things I'll need:

- [ ] login credentials for their MailChimp

The signup workflows would be one of:

- check box results in signing up upon submitting the form - How? 
    - pressing the button submits two forms: comment form and signup form
    - pressing button for signup form kicks something off serverside using the MailChimp API that subscribes the person.
- after submitting a comment, prompt to sign up through actual Mailchimp form
- after submitting a comment, send them an email prompting to them to subscribe

**Comment by benlk** [comment]
For possibility 1, we can use the "Mailchimp for WP" plugin to do the signup: https://kb.mc4wp.com/add-list-choice-comment-form/

But that's hauling in the entire plugin for a very limited purpose. 

Stackoverflow suggestions for something that submits two forms at once says that it either won't work or will be really weird for the user.

I *think* we can modify the WordPress comment emails to include a subscribe prompt, but I'm not sure what the particular WordPress function is.

**Comment by benlk** [comment]
RC suggested https://connect.mailchimp.com/integrations/chimpy-wordpress-plugin (https://codecanyon.net/item/chimpy-mailchimp-wordpress-plugin/6290216?ref=RightPress) which costs $29 for code and updates, and does the mailchimp signup in the comment box.

**Comment by kaylima** [comment]
NOTE: Updated, remaining estimate to use plugin mentioned by Ben above = 1-2 hours.

**Comment by benlk** [comment]
Installed on staging; added an api key  to the plugin. The plugin claims that it is unable to connect to the API, but it also successfully lists RR's MailChimp lists, so I'm not sure what's going on there. Tested subscribe on http://rrlargo.staging.wpengine.com/how-to-balance-kid-fun-and-mom-fun-at-the-sa-book-festival/#comment-3775087 and it worked. 

Configurable at Dashboard > Settings> MailChimp > Checkbox.

Looks like this works, with no styling needed.

Do we want to take this to production ahead of the rest of the changes in this batch?

**Comment by kaylima** [comment]
@benlk We want Rivard to review everything on staging and only move to production once we have sign-off from them. Thanks!

**Comment by benlk** [comment]
In response to their request that commenters be required to provide an email address when commenting - that's already the case (at least on staging). Settings > Discussion > Other Comment Settings > ☑︎ Comment author must fill out name and email

**Comment by benlk** [comment]
Deployed alongside #12.
