### ISSUE TITLE
Sticky Header Updates (2 hours)

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-rivard-report#8]
ESTIMATE: 2 hours

1. Go to http://rrlargo.staging.wpengine.com/

EXPECT 1: Make sticky header persistent as you scroll down that page
EXPECT 2: Add a donate button (see below)

![sticky-header](https://user-images.githubusercontent.com/15877728/29080578-57840592-7c1d-11e7-8077-eca7d7ddff08.jpg)

**Comment by benlk** [comment]
This requires creating a new version of the Largo nav JS, iirc.

The donate button may have a configuration option somewhere to enable it; I'm not sure.

**Comment by benlk** [comment]
A version of the desired scroll behavior was introduced in the staging branch in 56e4596, and is now deployed on http://rrlargo.staging.wpengine.com/. 

I've also changed the configuration of staging to remove the header social media buttons (Theme Options > Basic Settings > Social Media Links > Check this box if you want to show them in the header as well.) and to add a donation button in the header (Theme Options > Basic Settings > Donate Button)

The problem with this change to the header's donation and social media settings is that desktops no longer display the social media buttons and gain a duplicate donation button.

Do we care about that?

If they want the old desktop behavior for the global nav, I can put the "donate" button in the sticky nav directly.

**Comment by benlk** [comment]
Deployed in #12.
